# Generated by Django 2.2.16 on 2020-09-17 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(editable=False, upload_to='documents/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
