# Generated by Django 2.2.16 on 2020-09-17 17:39

from django.db import migrations, models
import findwords.models


class Migration(migrations.Migration):

    dependencies = [
        ('findwords', '0002_auto_20200917_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[findwords.models.validate_extension]),
        ),
    ]
