# Generated by Django 2.2.16 on 2020-09-20 15:19

from django.db import migrations, models
import django.db.models.deletion
import findwords.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('findwords', '0003_auto_20200917_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[findwords.models.validate_extension]),
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=50)),
                ('occurences', models.IntegerField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findwords.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phrase', models.TextField(blank=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findwords.Words')),
            ],
        ),
    ]
