# Generated by Django 2.2.16 on 2020-09-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findwords', '0005_auto_20200920_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrases',
            name='occurences',
        ),
    ]
